config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  get 'score/:id', to: 'articles#score', as: 'score_article'
  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.save!

		redirect_to @article
	end

	def show
		@article = Article.find(params[:id])
	end

	def score

		analyzer = Sentimental.new
		analyzer.load_defaults

		@article = Article.find(params[:id])
		@article.score = analyzer.score(@article.text)

		@article.save!

		redirect_to @article

	end

	private
	def article_params
		params.require(:article).permit(:title, :text, :score, :url, :publication, :tags)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :url %>
	<%= f.text_field :url %>

	<%= f.label :publication %>
	<%= f.text_field :publication %>

	<%= f.label :tags %>
	<%= f.text_field :tags %>

	<%= f.label :text %>
	<%= f.text_field :text %>

	<%= f.label :score %>
	<%= f.text_field :score %>

	<%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container"">
	<% @articles.each do |a| %>
		<%= link_to a.title, article_path(a) %>
		<br>
	<% end %>
</div>

app/views/articles/new.html.erb
New

<br>

<%= render 'form' %>

app/views/articles/show.html.erb
<%= @article.title %><br><br>
<%= @article.text %>
<br><br>

I think this article is about <%= @article.tags %> and score it <%= @article.score %>

<br><br>
<%= link_to "Rescore", score_article_url(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lexscore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>